name: populate_week
description: Populate the booking sheets for the next week.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0-171.0.dev

dependencies:
  excel: ^4.0.6
  path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
